// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index(title string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\"><script src=\"/static/vendor/js/htmx.min.js\"></script><script defer src=\"/static/vendor/js/alpine.persist.min.js\"></script><script defer src=\"/static/vendor/js/alpine.min.js\"></script><link rel=\"stylesheet\" href=\"/static/css/index.css\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 13, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</title></head><body x-data=\"{\n    streak: 0,\n    highestStreak: $persist(0),\n    get currentStreak() {\n      return this.streak;\n    },\n    get currentHighStreak() {\n      return this.highestStreak;\n    },\n    updateStreak() {\n      this.streak++;\n      if (this.streak &gt; this.highestStreak) {\n        this.highestStreak = this.streak;\n      }\n    },\n  }\"><div class=\"game\"><h1>Guess the emoji</h1><div class=\"streakCounters\"><div class=\"streakCounter\"><p title=\"Streak\">🔥 <span x-text=\"currentStreak\"></span></p></div><div class=\"streakCounter\"><p title=\"Highest Streak\">🏆 <span x-text=\"currentHighStreak\"></span></p></div></div><div hx-get=\"/emoji\" hx-trigger=\"load, reload from:body\" hx-target=\"#guessForm\"></div><form hx-post=\"/guess\" hx-trigger=\"submit\" hx-target=\"#response\" hx-swap=\"innerHTML\" id=\"guessForm\" class=\"guessForm\"></form><div id=\"response\"></div><div class=\"footer\"><p>Made by <a href=\"https://github.com/grqphical\">grqphical</a></p></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
